version: "3"

services:
  redis:
    image: redis:5
    networks:
      - backend

  db:
    image: postgres:11
    networks:
      - backend

  web:
    build: .
    # command: bin/rails server --port 3000 --binding 0.0.0.0
    command: bin/rake bot:run
    ports:
      - "3000:3000"
    networks:
      - backend
      - frontend
    depends_on:
      - redis
      - db
    environment:
      REDIS_URL: 'redis://redis:6379'
      CLUBHOUSE_TOKEN: ${CLUBHOUSE_TOKEN}
      SLACK_API_TOKEN: ${SLACK_API_TOKEN}
    volumes:
      - .:/usr/src/app
      - bundler_cache:/bundle
    tty: true
    stdin_open: true

networks:
  backend:
  frontend:

volumes:
  bundler_cache:
